(vl-load-com)

;;; ============================================================
;;; LSLabel â€” Auto Leader Label Generator
;;; Author : Ted Park
;;; Date   : 2025-11-25
;;; Free Distribution Version
;;; ============================================================

(defun _trim (s) (vl-string-trim " \t\r\n" s))
(defun _fixpct (s) (while (vl-string-search "%%%" s) (setq s (vl-string-subst "%" "%%%" s))) s)
(defun _objp (x) (eq (type x) 'VLA-OBJECT))
(defun _safe-put (o p v)
  (and (_objp o)
       (vlax-property-available-p o p)
       (not (vl-catch-all-error-p
              (vl-catch-all-apply 'vlax-put-property (list o p v))))))
(defun _get-ml-mtext (ml)
  (cond
    ((and (_objp ml) (vlax-method-applicable-p ml 'GetMText)) (vla-GetMText ml))
    ((vlax-property-available-p ml 'MText) (vla-get-MText ml))
    (T nil)))
(defun _get-style-name (obj)
  (cond
    ((and (_objp obj) (vlax-property-available-p obj 'StyleName))
     (vla-get-StyleName obj))
    ((and (_objp obj) (vlax-property-available-p obj 'TextStyleName))
     (vla-get-TextStyleName obj))))

(defun _enable-mask (ml scale / mt ok)
  (setq ok nil)
  (if (_safe-put ml 'TextBackgroundFill :vlax-true) (setq ok T))
  (_safe-put ml 'TextBackgroundScaleFactor scale)
  (if (not ok)
    (progn
      (if (_safe-put ml 'TextMask :vlax-true) (setq ok T))
      (_safe-put ml 'TextMaskScale scale)))
  (if (not ok)
    (progn
      (setq mt (_get-ml-mtext ml))
      (if (and mt (_objp mt))
        (progn
          (_safe-put mt 'BackgroundFill :vlax-true)
          (or (_safe-put mt 'BackgroundScaleFactor scale)
              (_safe-put mt 'TextBackgroundScaleFactor scale))
          (setq ok T)))))
  (vla-Update ml)
  ok)

(defun c:LSLabel (/ e1 e2 o1 o2 t1 t2 new pA pT doc ms pts ml olderr st mt h)

  (setq olderr *error*)
  (defun *error* (msg)
    (if (and msg (not (wcmatch (strcase msg) "*CANCEL*,*QUIT*")))
      (princ (strcat "\nError: " msg)))
    (while (> (getvar "CMDACTIVE") 0) (command))
    (setq *error* olderr)
    (princ))

  (setq e1 (car (entsel "\nSelect first TEXT/MTEXT (Slope %): ")))
  (setq e2 (car (entsel "\nSelect second TEXT/MTEXT (Level): ")))

  (if (and e1 e2)
    (progn
      (setq o1 (vlax-ename->vla-object e1)
            o2 (vlax-ename->vla-object e2)
            t1 (_fixpct (_trim (vla-get-TextString o1)))
            t2 (_fixpct (_trim (vla-get-TextString o2)))
            new (strcat "\\L" t1 "\\l\\P" t2)
            pA (getpoint "\nPick arrowhead point: ")
            pT (getpoint "\nPick text position: ")
            doc (vla-get-ActiveDocument (vlax-get-acad-object))
            ms  (vla-get-ModelSpace doc))

      (setq pts (vlax-make-safearray vlax-vbDouble '(0 . 5)))
      (vlax-safearray-fill pts (append (trans pA 1 0) (trans pT 1 0)))
      (setq ml (vla-AddMLeader ms pts 0))

      (_safe-put ml 'ArrowheadType 3)
      (_safe-put ml 'ArrowheadSize 3)
      (_safe-put ml 'ContentType 2)
      (vla-put-TextString ml new)

      (setq h (cond
                ((vlax-property-available-p o1 'Height) (* 2.0 (vla-get-Height o1)))
                ((vlax-property-available-p o1 'TextHeight) (* 2.0 (vla-get-TextHeight o1)))
                (T nil)))
      (if h (_safe-put ml 'TextHeight h))

      (setq st (_get-style-name o1))
      (if st
        (progn
          (_safe-put ml 'TextStyleName st)
          (_safe-put ml 'TextStyle st)
          (_safe-put ml 'MTextStyleName st)
          (setq mt (_get-ml-mtext ml))
          (if mt
            (progn
              (_safe-put mt 'StyleName st)
              (_safe-put mt 'TextStyleName st)
              (vla-Update mt)))
          (vla-Update ml)))

      (_safe-put ml 'LeaderLineColor 7)
      (if (vlax-property-available-p ml 'ArrowheadColor)
        (_safe-put ml 'ArrowheadColor 7))

      (_enable-mask ml 1.1)

      (vla-put-TextString o1 " ")
      (vla-put-TextString o2 " ")

      (princ "\nLSLabel created successfully.")
    )
    (prompt "\nPlease select two TEXT/MTEXT objects."))

  (setq *error* olderr)
  (princ))
